name: Deploy "main" branch to test instance

on:
    push:
        branches:
            - main

concurrency: deploy_test

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'

            - name: Deploy
              uses: deployphp/action@v1
              with:
                  private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
                  known-hosts: ${{ secrets.DEPLOY_SSH_KNOWN_HOSTS }}
                  deployer-version: 7.3.3
                  dep: deploy test
